import logging
from flask import Flask, render_template_string
from typing import Final

# Configure logging for production monitoring
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Constants for Server Configuration
HOST: Final[str] = "0.0.0.0"
PORT: Final[int] = 5000
DEBUG: Final[bool] = False

# HTML/CSS/JS Template implementing the requested Architecture Design
# This includes the Game Board, Status Indicator, and Game Logic Engine
TIC_TAC_TOE_TEMPLATE: Final[str] = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Production Tic Tac Toe</title>
    <style>
        :root {
            --primary-color: #2c3e50;
            --accent-color: #3498db;
            --text-color: #ecf0f1;
            --cell-size: 100px;
            --border-radius: 8px;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: var(--primary-color);
            color: var(--text-color);
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .game-container {
            text-align: center;
        }

        .status-indicator {
            margin-bottom: 20px;
            font-size: 1.5rem;
            font-weight: bold;
        }

        /* Grid Layout for the Game Board */
        .board {
            display: grid;
            grid-template-columns: repeat(3, var(--cell-size));
            grid-template-rows: repeat(3, var(--cell-size));
            gap: 10px;
            background-color: #34495e;
            padding: 10px;
            border-radius: var(--border-radius);
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
        }

        .cell {
            width: var(--cell-size);
            height: var(--cell-size);
            background-color: var(--primary-color);
            border-radius: 4px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2.5rem;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .cell:hover {
            background-color: #3d566e;
        }

        .cell.taken {
            cursor: not-allowed;
        }

        .reset-btn {
            margin-top: 30px;
            padding: 10px 25px;
            font-size: 1rem;
            background-color: var(--accent-color);
            color: white;
            border: none;
            border-radius: var(--border-radius);
            cursor: pointer;
            transition: transform 0.2s ease;
        }

        .reset-btn:active {
            transform: scale(0.95);
        }

        .winner-highlight {
            color: #2ecc71;
        }
    </style>
</head>
<body>

    <div class="game-container">
        <h1>Tic Tac Toe</h1>
        <div id="status" class="status-indicator">Player X's Turn</div>
        <div id="board" class="board">
            <!-- Cells generated by JavaScript -->
        </div>
        <button id="reset" class="reset-btn">Reset Game</button>
    </div>

    <script>
        /**
         * Game Logic Engine using Module Pattern
         * Handles state management and win condition validation
         */
        const GameEngine = (() => {
            let state = {
                board: Array(9).fill(null),
                currentPlayer: 'X',
                isGameOver: false,
                winner: null
            };

            const winPatterns = [
                [0, 1, 2], [3, 4, 5], [6, 7, 8], // Rows
                [0, 3, 6], [1, 4, 7], [2, 5, 8], // Cols
                [0, 4, 8], [2, 4, 6]             // Diagonals
            ];

            const checkWinner = () => {
                for (let pattern of winPatterns) {
                    const [a, b, c] = pattern;
                    if (state.board[a] && state.board[a] === state.board[b] && state.board[a] === state.board[c]) {
                        return state.board[a];
                    }
                }
                return state.board.includes(null) ? null : 'Draw';
            };

            return {
                makeMove: (index) => {
                    if (state.board[index] || state.isGameOver) return false;
                    
                    state.board[index] = state.currentPlayer;
                    const result = checkWinner();
                    
                    if (result) {
                        state.isGameOver = true;
                        state.winner = result;
                    } else {
                        state.currentPlayer = state.currentPlayer === 'X' ? 'O' : 'X';
                    }
                    return true;
                },
                reset: () => {
                    state = {
                        board: Array(9).fill(null),
                        currentPlayer: 'X',
                        isGameOver: false,
                        winner: null
                    };
                },
                getState: () => ({ ...state })
            };
        })();

        /**
         * UI Controller using Observer Pattern principles
         * Manages DOM updates based on GameEngine state
         */
        const UIController = (() => {
            const boardElement = document.getElementById('board');
            const statusElement = document.getElementById('status');
            const resetBtn = document.getElementById('reset');

            const render = () => {
                const state = GameEngine.getState();
                boardElement.innerHTML = '';
                
                state.board.forEach((cell, index) => {
                    const cellDiv = document.createElement('div');
                    cellDiv.classList.add('cell');
                    if (cell) cellDiv.classList.add('taken');
                    cellDiv.textContent = cell || '';
                    cellDiv.addEventListener('click', () => handleCellClick(index));
                    boardElement.appendChild(cellDiv);
                });

                if (state.isGameOver) {
                    if (state.winner === 'Draw') {
                        statusElement.textContent = "It's a Draw!";
                    } else {
                        statusElement.innerHTML = `Winner: <span class="winner-highlight">${state.winner}</span>`;
                    }
                } else {
                    statusElement.textContent = `Player ${state.currentPlayer}'s Turn`;
                }
            };

            const handleCellClick = (index) => {
                if (GameEngine.makeMove(index)) {
                    render();
                }
            };

            resetBtn.addEventListener('click', () => {
                GameEngine.reset();
                render();
            });

            return { init: render };
        })();

        // Initialize Application
        document.addEventListener('DOMContentLoaded', UIController.init);
    </script>
</body>
</html>
"""

class TicTacToeApp:
    """
    Production-ready Flask Application wrapper for Tic Tac Toe.
    Encapsulates server logic and template rendering.
    """

    def __init__(self, name: str = __name__):
        """
        Initializes the Flask application and defines routes.
        
        :param name: The name of the application module.
        """
        self.app = Flask(name)
        self._setup_routes()

    def _setup_routes(self) -> None:
        """
        Defines the routing table for the web application.
        """
        @self.app.route('/')
        def index() -> str:
            """
            Serves the main Tic Tac Toe game page.
            
            :return: Rendered HTML string.
            """
            try:
                return render_template_string(TIC_TAC_TOE_TEMPLATE)
            except Exception as e:
                logger.error(f"Error rendering template: {e}")
                return "Internal Server Error", 500

    def run(self, host: str = HOST, port: int = PORT, debug: bool = DEBUG) -> None:
        """
        Starts the Flask development server.
        
        :param host: Network address to bind to.
        :param port: Port to listen on.
        :param debug: Enable/disable debug mode.
        """
        try:
            logger.info(f"Starting Tic Tac Toe server on {host}:{port}")
            self.app.run(host=host, port=port, debug=debug)
        except Exception as e:
            logger.critical(f"Server failed to start: {e}")

if __name__ == "__main__":
    # Instantiate and run the production-ready game server
    game_server = TicTacToeApp()
    game_server.run()